# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpc.worker_pb2 as worker__pb2


class WorkerSvcStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send_task = channel.stream_stream(
                '/WorkerSvc/send_task',
                request_serializer=worker__pb2.TaskRequest.SerializeToString,
                response_deserializer=worker__pb2.TaskResponse.FromString,
                )


class WorkerSvcServicer(object):
    """Missing associated documentation comment in .proto file"""

    def send_task(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerSvcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send_task': grpc.stream_stream_rpc_method_handler(
                    servicer.send_task,
                    request_deserializer=worker__pb2.TaskRequest.FromString,
                    response_serializer=worker__pb2.TaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WorkerSvc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkerSvc(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def send_task(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/WorkerSvc/send_task',
            worker__pb2.TaskRequest.SerializeToString,
            worker__pb2.TaskResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
