// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.12.1
// source: protos/dispacher.proto

package protos

import (
	context "context"
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TaskResult int32

const (
	TaskResult_FIN  TaskResult = 0
	TaskResult_FAIL TaskResult = 1
)

// Enum value maps for TaskResult.
var (
	TaskResult_name = map[int32]string{
		0: "FIN",
		1: "FAIL",
	}
	TaskResult_value = map[string]int32{
		"FIN":  0,
		"FAIL": 1,
	}
)

func (x TaskResult) Enum() *TaskResult {
	p := new(TaskResult)
	*p = x
	return p
}

func (x TaskResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskResult) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_dispacher_proto_enumTypes[0].Descriptor()
}

func (TaskResult) Type() protoreflect.EnumType {
	return &file_protos_dispacher_proto_enumTypes[0]
}

func (x TaskResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskResult.Descriptor instead.
func (TaskResult) EnumDescriptor() ([]byte, []int) {
	return file_protos_dispacher_proto_rawDescGZIP(), []int{0}
}

type TaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic   string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Channel string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_dispacher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_dispacher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_protos_dispacher_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TaskRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageID []byte `protobuf:"bytes,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
	Payload   []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_dispacher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_dispacher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_protos_dispacher_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetMessageID() []byte {
	if x != nil {
		return x.MessageID
	}
	return nil
}

func (x *TaskResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type FinTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic     string     `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Channel   string     `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	MessageID []byte     `protobuf:"bytes,3,opt,name=messageID,proto3" json:"messageID,omitempty"`
	Result    TaskResult `protobuf:"varint,4,opt,name=result,proto3,enum=protos.TaskResult" json:"result,omitempty"`
	Payload   []byte     `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *FinTaskRequest) Reset() {
	*x = FinTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_dispacher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinTaskRequest) ProtoMessage() {}

func (x *FinTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_dispacher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinTaskRequest.ProtoReflect.Descriptor instead.
func (*FinTaskRequest) Descriptor() ([]byte, []int) {
	return file_protos_dispacher_proto_rawDescGZIP(), []int{2}
}

func (x *FinTaskRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *FinTaskRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *FinTaskRequest) GetMessageID() []byte {
	if x != nil {
		return x.MessageID
	}
	return nil
}

func (x *FinTaskRequest) GetResult() TaskResult {
	if x != nil {
		return x.Result
	}
	return TaskResult_FIN
}

func (x *FinTaskRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type FinTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinTaskResponse) Reset() {
	*x = FinTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_dispacher_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinTaskResponse) ProtoMessage() {}

func (x *FinTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_dispacher_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinTaskResponse.ProtoReflect.Descriptor instead.
func (*FinTaskResponse) Descriptor() ([]byte, []int) {
	return file_protos_dispacher_proto_rawDescGZIP(), []int{3}
}

var File_protos_dispacher_proto protoreflect.FileDescriptor

var file_protos_dispacher_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x22, 0x3d, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22,
	0x46, 0x0a, 0x0c, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xa4, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x11,
	0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2a, 0x1f, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x07, 0x0a, 0x03, 0x46, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c,
	0x10, 0x01, 0x32, 0x80, 0x01, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x72, 0x12, 0x35, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x66, 0x69, 0x6e, 0x5f,
	0x74, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x69,
	0x6e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_dispacher_proto_rawDescOnce sync.Once
	file_protos_dispacher_proto_rawDescData = file_protos_dispacher_proto_rawDesc
)

func file_protos_dispacher_proto_rawDescGZIP() []byte {
	file_protos_dispacher_proto_rawDescOnce.Do(func() {
		file_protos_dispacher_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_dispacher_proto_rawDescData)
	})
	return file_protos_dispacher_proto_rawDescData
}

var file_protos_dispacher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_dispacher_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_dispacher_proto_goTypes = []interface{}{
	(TaskResult)(0),         // 0: protos.TaskResult
	(*TaskRequest)(nil),     // 1: protos.TaskRequest
	(*TaskResponse)(nil),    // 2: protos.TaskResponse
	(*FinTaskRequest)(nil),  // 3: protos.FinTaskRequest
	(*FinTaskResponse)(nil), // 4: protos.FinTaskResponse
}
var file_protos_dispacher_proto_depIdxs = []int32{
	0, // 0: protos.FinTaskRequest.result:type_name -> protos.TaskResult
	1, // 1: protos.Dispatcher.get_task:input_type -> protos.TaskRequest
	3, // 2: protos.Dispatcher.fin_task:input_type -> protos.FinTaskRequest
	2, // 3: protos.Dispatcher.get_task:output_type -> protos.TaskResponse
	4, // 4: protos.Dispatcher.fin_task:output_type -> protos.FinTaskResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_dispacher_proto_init() }
func file_protos_dispacher_proto_init() {
	if File_protos_dispacher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_dispacher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_dispacher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_dispacher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_dispacher_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_dispacher_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_dispacher_proto_goTypes,
		DependencyIndexes: file_protos_dispacher_proto_depIdxs,
		EnumInfos:         file_protos_dispacher_proto_enumTypes,
		MessageInfos:      file_protos_dispacher_proto_msgTypes,
	}.Build()
	File_protos_dispacher_proto = out.File
	file_protos_dispacher_proto_rawDesc = nil
	file_protos_dispacher_proto_goTypes = nil
	file_protos_dispacher_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DispatcherClient is the client API for Dispatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DispatcherClient interface {
	GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	FinTask(ctx context.Context, in *FinTaskRequest, opts ...grpc.CallOption) (*FinTaskResponse, error)
}

type dispatcherClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatcherClient(cc grpc.ClientConnInterface) DispatcherClient {
	return &dispatcherClient{cc}
}

func (c *dispatcherClient) GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, "/protos.Dispatcher/get_task", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatcherClient) FinTask(ctx context.Context, in *FinTaskRequest, opts ...grpc.CallOption) (*FinTaskResponse, error) {
	out := new(FinTaskResponse)
	err := c.cc.Invoke(ctx, "/protos.Dispatcher/fin_task", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatcherServer is the server API for Dispatcher service.
type DispatcherServer interface {
	GetTask(context.Context, *TaskRequest) (*TaskResponse, error)
	FinTask(context.Context, *FinTaskRequest) (*FinTaskResponse, error)
}

// UnimplementedDispatcherServer can be embedded to have forward compatible implementations.
type UnimplementedDispatcherServer struct {
}

func (*UnimplementedDispatcherServer) GetTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (*UnimplementedDispatcherServer) FinTask(context.Context, *FinTaskRequest) (*FinTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinTask not implemented")
}

func RegisterDispatcherServer(s *grpc.Server, srv DispatcherServer) {
	s.RegisterService(&_Dispatcher_serviceDesc, srv)
}

func _Dispatcher_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Dispatcher/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherServer).GetTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatcher_FinTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherServer).FinTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Dispatcher/FinTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherServer).FinTask(ctx, req.(*FinTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dispatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Dispatcher",
	HandlerType: (*DispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get_task",
			Handler:    _Dispatcher_GetTask_Handler,
		},
		{
			MethodName: "fin_task",
			Handler:    _Dispatcher_FinTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/dispacher.proto",
}
