// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: telepathy.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MethodEnum int32

const (
	MethodEnum_UNARY         MethodEnum = 0
	MethodEnum_CLIENT_STREAM MethodEnum = 1
	MethodEnum_SERVER_STREAM MethodEnum = 2
	MethodEnum_DUPLEX_STREAM MethodEnum = 3
)

// Enum value maps for MethodEnum.
var (
	MethodEnum_name = map[int32]string{
		0: "UNARY",
		1: "CLIENT_STREAM",
		2: "SERVER_STREAM",
		3: "DUPLEX_STREAM",
	}
	MethodEnum_value = map[string]int32{
		"UNARY":         0,
		"CLIENT_STREAM": 1,
		"SERVER_STREAM": 2,
		"DUPLEX_STREAM": 3,
	}
)

func (x MethodEnum) Enum() *MethodEnum {
	p := new(MethodEnum)
	*p = x
	return p
}

func (x MethodEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MethodEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_telepathy_proto_enumTypes[0].Descriptor()
}

func (MethodEnum) Type() protoreflect.EnumType {
	return &file_telepathy_proto_enumTypes[0]
}

func (x MethodEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MethodEnum.Descriptor instead.
func (MethodEnum) EnumDescriptor() ([]byte, []int) {
	return file_telepathy_proto_rawDescGZIP(), []int{0}
}

type InnerTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string     `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MethodName  string     `protobuf:"bytes,2,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	MethodType  MethodEnum `protobuf:"varint,3,opt,name=method_type,json=methodType,proto3,enum=Microsoft.Telepathy.ProtoBuf.MethodEnum" json:"method_type,omitempty"`
	SessionId   string     `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientId    string     `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MessageId   string     `protobuf:"bytes,6,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Msg         []byte     `protobuf:"bytes,7,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *InnerTask) Reset() {
	*x = InnerTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_telepathy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerTask) ProtoMessage() {}

func (x *InnerTask) ProtoReflect() protoreflect.Message {
	mi := &file_telepathy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerTask.ProtoReflect.Descriptor instead.
func (*InnerTask) Descriptor() ([]byte, []int) {
	return file_telepathy_proto_rawDescGZIP(), []int{0}
}

func (x *InnerTask) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *InnerTask) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *InnerTask) GetMethodType() MethodEnum {
	if x != nil {
		return x.MethodType
	}
	return MethodEnum_UNARY
}

func (x *InnerTask) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InnerTask) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *InnerTask) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *InnerTask) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type InnerResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg []byte `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	// state_code 0: success, 1: failed
	StateCode   int32  `protobuf:"varint,2,opt,name=state_code,json=stateCode,proto3" json:"state_code,omitempty"`
	StateDetail string `protobuf:"bytes,3,opt,name=state_detail,json=stateDetail,proto3" json:"state_detail,omitempty"`
	SessionId   string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientId    string `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MessageId   string `protobuf:"bytes,6,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *InnerResult) Reset() {
	*x = InnerResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_telepathy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerResult) ProtoMessage() {}

func (x *InnerResult) ProtoReflect() protoreflect.Message {
	mi := &file_telepathy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerResult.ProtoReflect.Descriptor instead.
func (*InnerResult) Descriptor() ([]byte, []int) {
	return file_telepathy_proto_rawDescGZIP(), []int{1}
}

func (x *InnerResult) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *InnerResult) GetStateCode() int32 {
	if x != nil {
		return x.StateCode
	}
	return 0
}

func (x *InnerResult) GetStateDetail() string {
	if x != nil {
		return x.StateDetail
	}
	return ""
}

func (x *InnerResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InnerResult) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *InnerResult) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_telepathy_proto protoreflect.FileDescriptor

var file_telepathy_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1c, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x6f, 0x66, 0x74, 0x2e, 0x54, 0x65, 0x6c,
	0x65, 0x70, 0x61, 0x74, 0x68, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x22,
	0x87, 0x02, 0x0a, 0x09, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x49, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x6f,
	0x66, 0x74, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x79, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x42, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x45, 0x6e, 0x75, 0x6d,
	0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xbc, 0x01, 0x0a, 0x0b, 0x49, 0x6e,
	0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x2a, 0x50, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x41, 0x52, 0x59, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x52, 0x45,
	0x41, 0x4d, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x53,
	0x54, 0x52, 0x45, 0x41, 0x4d, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x55, 0x50, 0x4c, 0x45,
	0x58, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x10, 0x03, 0x42, 0x1f, 0xaa, 0x02, 0x1c, 0x4d,
	0x69, 0x63, 0x72, 0x6f, 0x73, 0x6f, 0x66, 0x74, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x70, 0x61, 0x74,
	0x68, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_telepathy_proto_rawDescOnce sync.Once
	file_telepathy_proto_rawDescData = file_telepathy_proto_rawDesc
)

func file_telepathy_proto_rawDescGZIP() []byte {
	file_telepathy_proto_rawDescOnce.Do(func() {
		file_telepathy_proto_rawDescData = protoimpl.X.CompressGZIP(file_telepathy_proto_rawDescData)
	})
	return file_telepathy_proto_rawDescData
}

var file_telepathy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_telepathy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_telepathy_proto_goTypes = []interface{}{
	(MethodEnum)(0),     // 0: Microsoft.Telepathy.ProtoBuf.MethodEnum
	(*InnerTask)(nil),   // 1: Microsoft.Telepathy.ProtoBuf.InnerTask
	(*InnerResult)(nil), // 2: Microsoft.Telepathy.ProtoBuf.InnerResult
}
var file_telepathy_proto_depIdxs = []int32{
	0, // 0: Microsoft.Telepathy.ProtoBuf.InnerTask.method_type:type_name -> Microsoft.Telepathy.ProtoBuf.MethodEnum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_telepathy_proto_init() }
func file_telepathy_proto_init() {
	if File_telepathy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_telepathy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_telepathy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_telepathy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telepathy_proto_goTypes,
		DependencyIndexes: file_telepathy_proto_depIdxs,
		EnumInfos:         file_telepathy_proto_enumTypes,
		MessageInfos:      file_telepathy_proto_msgTypes,
	}.Build()
	File_telepathy_proto = out.File
	file_telepathy_proto_rawDesc = nil
	file_telepathy_proto_goTypes = nil
	file_telepathy_proto_depIdxs = nil
}
